### ISSUE TITLE
Server Port hard coded to 8000

### ISSUE THREAD

**Issue by NogsMPLS** [JedWatson/react-component-gulp-tasks#12]
Might be nice to have server port configurable, instead of hard coded to 8000 like it is now in the tasks/dev.js file.

Right now I am having to change the actual file in my node_modules folder to a different number in order to get the Elemental UI dev server up.

**Comment by JedWatson** [comment]
Thanks for catching that @NogsMPLS 

I've fixed this so the port can now be set with the environment variable `PORT`, as standard on most node.js web apps. Released with version `0.7.5`
