### ISSUE TITLE
Handle devDependencies in examples

### ISSUE THREAD

**Issue by dantman** [JedWatson/react-component-gulp-tasks#14]
The example building code doesn't take `devDependencies` into account.

ie: If you add something to `devDependencies` that's only needed for the examples and tests. Then require it from the examples. The build script will generate an app.js with a bunch of duplicate deps. This will include a second copy of React which will cause the examples to break.

This is important because React has been split into `react` and `react-dom`.

Both `react-input-autosize` and `react-select` do not require `react-dom` in peerDeps as functions from there are not needed in the components. However the examples do require `react-dom` to do things correctly and avoid deprecation warnings.

This means that for examples and tests we'll need to add `react-dom` to the `devDependencies`. But that will break the examples until this is fixed.

**Comment by JedWatson** [comment]
So I think the answer is to explicitly set the dependencies (including `react-dom`) for `react-input-autosize` and `react-select` with the `dependencies` key in `config`.

The current system is a shortcut for when the package dependencies and peerDependencies are enough, but `devDependencies` will contain a whole lot of packages that should never be bundled in the examples.

I'll add the explicit dependencies to both those projects.
